// ===================================================================
//  hw_config.h — Generated by tools/gen_firmware_config.py; do not edit manually
//  Source: config/hardware.yaml
//  Autonomous Laboratory v6 — Eight peristaltic pumps, automated cleaning, syringe pump, two valves and 10 Hz gravimetric feedback
// ===================================================================
#ifndef HW_CONFIG_H
#define HW_CONFIG_H

// ---------- Two DM542J drivers ----------
#define PUL1 22
#define DIR1 23
#define ENA1 24
#define PUL2 25
#define DIR2 26
#define ENA2 27

// ---------- Relays: motor n is controlled by D<n> ----------
#define FIRST_MOTOR 2
#define LAST_MOTOR  9
#define GROUP_B_FIRST 6

#define MAX_SPS   8000.0
#define SETTLE_MS 60

// ---------- Volume conversions used by the interface ----------
#define PULSES_PER_ML   4237.007613F
#define PULSES_PER_REV  1600L
#define MAX_FLOW_UL_MIN 80000L

// ---------- Cleaning: water intake, simultaneous operation, then OUT drainage ----------
#define CLEAN_WATER_MOTOR 2
#define CLEAN_OUT_MOTOR 8
#define CLEAN_WATER_SPS 2825.0F
#define CLEAN_OUT_SPS 2825.0F
#define CLEAN_WATER_LEAD_MS 30000UL
#define CLEAN_OVERLAP_MS 45000UL
#define CLEAN_OUT_TAIL_MS 45000UL

// ---------- Solenoid valves ----------
#define NUM_VALVES 2
#define VALVE_PIN_LIST { 10, 11 }
#define MOTOR_VALVE_LIST { 1, 0, 0, 0, 0, 0, 0, 2 }
#define VALVE_OPEN_BEFORE_MS 1000UL
#define VALVE_CLOSE_AFTER_MS 1000UL

// ---------- Syringe pump ----------
#define PUMP_SERIAL Serial1          // TX1=D18, RX1=D19
#define PUMP_BAUD 9600UL
#define PUMP_ADDR 0
#define PUMP_FULL_STROKE 12000L
#define PUMP_DEFAULT_SYRINGE_UL 5000L

// ---------- Scale transmitter ----------
#define SCALE_SERIAL Serial2         // TX2=D16, RX2=D17
#define SCALE_DE_PIN 36
#define SCALE_STREAM_HZ 10
#define SCALE_AVG_SAMPLES 1
#define SCALE_STABLE_G 0.015000F
#define SCALE_BAUD 9600L
#define SCALE_ADDR 1
#define SCALE_FUNC 3
#define SCALE_REG  0
#define SCALE_FMT  1

#endif  // HW_CONFIG_H
