#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 10, 2025 10:05:50 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
from queue import Queue

_location = os.path.dirname(__file__)

import control_gui_support

# =============================================================================
# import Spectra_Viewer
# =============================================================================

_bgcolor = "#f0f0f0"
_fgcolor = "#000000"
_tabfg1 = "black"
_tabfg2 = "white"
_bgmode = "light"
_tabbg1 = "#d9d9d9"
_tabbg2 = "gray40"

_style_code_ran = 0


def _style_code():
    global _style_code_ran
    if _style_code_ran:
        return
    style = ttk.Style()
    if "vista" in style.theme_names():
        style.theme_use("vista")
    elif "clam" in style.theme_names():
        style.theme_use("clam")
    style.configure(".", font="TkDefaultFont")
    _style_code_ran = 1


class Toplevel1:
    def __init__(self, save_path, select_mode, top=None):

        self.save_path = save_path
        self.select_mode = select_mode
        self.value_list = ["Cu", "Ni", "Pb", "Zn", "Pd", "Au"]

        top.geometry("1032x583+494+214")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title(f"Mode {select_mode}")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.combobox = tk.StringVar()

        self.TNotebook1 = ttk.Notebook(self.top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=1.012, relwidth=1.005)

        self.parameter_setting = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.parameter_setting, padding=3)
        self.TNotebook1.tab(
            0,
            text="""Parameter Setting""",
            compound="left",
            underline="""-1""",
        )
        self.parameter_setting.configure(highlightcolor="#000000")

        self.result = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.result, padding=3)
        self.TNotebook1.tab(
            1,
            text="""Result""",
            compound="left",
            underline="""-1""",
        )
        self.result.configure(highlightcolor="#000000")

        self.analysis = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.analysis, padding=3)
        self.TNotebook1.tab(
            2,
            text="""Analysis""",
            compound="left",
            underline="""-1""",
        )
        self.analysis.configure(highlightcolor="#000000")

        self.combobox_var_1 = tk.StringVar()
        self.metal_combobox_1 = ttk.Combobox(self.parameter_setting)
        self.metal_combobox_1.place(relx=0.046, rely=0.172, relheight=0.067, relwidth=0.1)
        self.metal_combobox_1.configure(values=self.value_list)
        self.metal_combobox_1.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.metal_combobox_1.configure(textvariable=self.combobox_var_1)
        self.metal_combobox_1.configure(foreground="#000000")
        self.combobox_var_1.set("Metal 1")

        self.combobox_var_2 = tk.StringVar()
        self.metal_combobox_2 = ttk.Combobox(self.parameter_setting)
        self.metal_combobox_2.place(relx=0.046, rely=0.309, relheight=0.067, relwidth=0.1)
        self.metal_combobox_2.configure(values=self.value_list)
        self.metal_combobox_2.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.metal_combobox_2.configure(textvariable=self.combobox_var_2)
        self.metal_combobox_2.configure(foreground="#000000")
        self.combobox_var_2.set("Metal 2")

        self.combobox_var_3 = tk.StringVar()
        self.metal_combobox_3 = ttk.Combobox(self.parameter_setting)
        self.metal_combobox_3.place(relx=0.046, rely=0.446, relheight=0.067, relwidth=0.1)
        self.metal_combobox_3.configure(values=self.value_list)
        self.metal_combobox_3.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.metal_combobox_3.configure(textvariable=self.combobox_var_3)
        self.metal_combobox_3.configure(foreground="#000000")
        self.combobox_var_3.set("Metal 3")

        self.combobox_var_4 = tk.StringVar()
        self.metal_combobox_4 = ttk.Combobox(self.parameter_setting)
        self.metal_combobox_4.place(relx=0.046, rely=0.583, relheight=0.067, relwidth=0.1)
        self.metal_combobox_4.configure(values=self.value_list)
        self.metal_combobox_4.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.metal_combobox_4.configure(textvariable=self.combobox_var_4)
        self.metal_combobox_4.configure(foreground="#000000")
        self.combobox_var_4.set("Metal 4")

        self.combobox_var_5 = tk.StringVar()
        self.metal_combobox_5 = ttk.Combobox(self.parameter_setting)
        self.metal_combobox_5.place(relx=0.046, rely=0.72, relheight=0.067, relwidth=0.1)
        self.metal_combobox_5.configure(values=self.value_list)
        self.metal_combobox_5.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.metal_combobox_5.configure(textvariable=self.combobox_var_5)
        self.metal_combobox_5.configure(foreground="#000000")
        self.combobox_var_5.set("Metal 5")

        self.loop = tk.Label(self.parameter_setting)
        self.loop.place(relx=0.64, rely=0.446, height=34, width=148)
        self.loop.configure(activebackground="#d9d9d9")
        self.loop.configure(activeforeground="black")
        self.loop.configure(disabledforeground="#b4b4b4")
        self.loop.configure(font="-family {Times New Roman} -size 20")
        self.loop.configure(foreground="#000000")
        self.loop.configure(highlightcolor="#000000")
        self.loop.configure(text="""Loop""")

        self.conductivity = tk.Label(self.parameter_setting)
        self.conductivity.place(relx=0.63, rely=0.309, height=34, width=170)
        self.conductivity.configure(activebackground="#d9d9d9")
        self.conductivity.configure(activeforeground="black")
        self.conductivity.configure(disabledforeground="#b4b4b4")
        self.conductivity.configure(font="-family {Times New Roman} -size 20")
        self.conductivity.configure(foreground="#000000")
        self.conductivity.configure(highlightcolor="#000000")
        self.conductivity.configure(text="""Conductivity""")

        self.voltage = tk.Label(self.parameter_setting)
        self.voltage.place(relx=0.64, rely=0.172, height=34, width=150)
        self.voltage.configure(activebackground="#d9d9d9")
        self.voltage.configure(activeforeground="black")
        self.voltage.configure(disabledforeground="#b4b4b4")
        self.voltage.configure(font="-family {Times New Roman} -size 20")
        self.voltage.configure(foreground="#000000")
        self.voltage.configure(highlightcolor="#000000")
        self.voltage.configure(text="""Voltage""")

        self.ontime = tk.Label(self.parameter_setting)
        self.ontime.place(relx=0.32, rely=0.172, height=34, width=146)
        self.ontime.configure(activebackground="#d9d9d9")
        self.ontime.configure(activeforeground="black")
        self.ontime.configure(disabledforeground="#b4b4b4")
        self.ontime.configure(font="-family {Times New Roman} -size 20")
        self.ontime.configure(foreground="#000000")
        self.ontime.configure(highlightcolor="#000000")
        self.ontime.configure(text="""Ontime""")

        self.offtime = tk.Label(self.parameter_setting)
        self.offtime.place(relx=0.32, rely=0.309, height=33, width=146)
        self.offtime.configure(activebackground="#d9d9d9")
        self.offtime.configure(activeforeground="black")
        self.offtime.configure(disabledforeground="#b4b4b4")
        self.offtime.configure(font="-family {Times New Roman} -size 20")
        self.offtime.configure(foreground="#000000")
        self.offtime.configure(highlightcolor="#000000")
        self.offtime.configure(text="""Offtime""")

        self.cycle = tk.Label(self.parameter_setting)
        self.cycle.place(relx=0.32, rely=0.446, height=34, width=146)
        self.cycle.configure(activebackground="#d9d9d9")
        self.cycle.configure(activeforeground="black")
        self.cycle.configure(disabledforeground="#b4b4b4")
        self.cycle.configure(font="-family {Times New Roman} -size 20")
        self.cycle.configure(foreground="#000000")
        self.cycle.configure(highlightcolor="#000000")
        self.cycle.configure(text="""Cycle""")

        self.spectra = tk.Label(self.parameter_setting)
        self.spectra.place(relx=0.32, rely=0.703, height=32, width=146)
        self.spectra.configure(activebackground="#d9d9d9")
        self.spectra.configure(activeforeground="black")
        self.spectra.configure(disabledforeground="#b4b4b4")
        self.spectra.configure(font="-family {Times New Roman} -size 20")
        self.spectra.configure(foreground="#000000")
        self.spectra.configure(highlightcolor="#000000")
        self.spectra.configure(text="""Spectra""")

        self.interval = tk.Label(self.parameter_setting)
        self.interval.place(relx=0.32, rely=0.755, height=33, width=146)
        self.interval.configure(activebackground="#d9d9d9")
        self.interval.configure(activeforeground="black")
        self.interval.configure(disabledforeground="#b4b4b4")
        self.interval.configure(font="-family {Times New Roman} -size 20")
        self.interval.configure(foreground="#000000")
        self.interval.configure(highlightcolor="#000000")
        self.interval.configure(text="""Interval""")

        self.time = tk.Label(self.parameter_setting)
        self.time.place(relx=0.32, rely=0.617, height=33, width=151)
        self.time.configure(activebackground="#d9d9d9")
        self.time.configure(activeforeground="black")
        self.time.configure(disabledforeground="#b4b4b4")
        self.time.configure(font="-family {Times New Roman} -size 20")
        self.time.configure(foreground="#000000")
        self.time.configure(highlightcolor="#000000")
        self.time.configure(text="""Time""")

        self.integration = tk.Label(self.parameter_setting)
        self.integration.place(relx=0.32, rely=0.566, height=33, width=146)
        self.integration.configure(activebackground="#d9d9d9")
        self.integration.configure(activeforeground="black")
        self.integration.configure(disabledforeground="#b4b4b4")
        self.integration.configure(font="-family {Times New Roman} -size 20")
        self.integration.configure(foreground="#000000")
        self.integration.configure(highlightcolor="#000000")
        self.integration.configure(text="""Integration""")

        self.metal_entry_1 = tk.Entry(self.parameter_setting)
        self.metal_entry_1.place(relx=0.155, rely=0.172, height=37, relwidth=0.14)
        self.metal_entry_1.configure(background="#f0f0f0")
        self.metal_entry_1.configure(disabledforeground="#b4b4b4")
        self.metal_entry_1.configure(font="-family {Times New Roman} -size 14")
        self.metal_entry_1.configure(foreground="#000000")
        self.metal_entry_1.configure(highlightcolor="#000000")
        self.metal_entry_1.configure(selectbackground="#d9d9d9")
        self.metal_entry_1.configure(selectforeground="black")

        self.metal_entry_2 = tk.Entry(self.parameter_setting)
        self.metal_entry_2.place(relx=0.155, rely=0.309, height=37, relwidth=0.14)
        self.metal_entry_2.configure(background="#f0f0f0")
        self.metal_entry_2.configure(disabledforeground="#b4b4b4")
        self.metal_entry_2.configure(font="-family {Times New Roman} -size 14")
        self.metal_entry_2.configure(foreground="#000000")
        self.metal_entry_2.configure(highlightcolor="#000000")
        self.metal_entry_2.configure(selectbackground="#d9d9d9")
        self.metal_entry_2.configure(selectforeground="black")

        self.metal_entry_3 = tk.Entry(self.parameter_setting)
        self.metal_entry_3.place(relx=0.155, rely=0.446, height=37, relwidth=0.14)
        self.metal_entry_3.configure(background="#f0f0f0")
        self.metal_entry_3.configure(disabledforeground="#b4b4b4")
        self.metal_entry_3.configure(font="-family {Times New Roman} -size 14")
        self.metal_entry_3.configure(foreground="#000000")
        self.metal_entry_3.configure(highlightcolor="#000000")
        self.metal_entry_3.configure(selectbackground="#d9d9d9")
        self.metal_entry_3.configure(selectforeground="black")

        self.metal_entry_4 = tk.Entry(self.parameter_setting)
        self.metal_entry_4.place(relx=0.155, rely=0.583, height=37, relwidth=0.14)
        self.metal_entry_4.configure(background="#f0f0f0")
        self.metal_entry_4.configure(disabledforeground="#b4b4b4")
        self.metal_entry_4.configure(font="-family {Times New Roman} -size 14")
        self.metal_entry_4.configure(foreground="#000000")
        self.metal_entry_4.configure(highlightcolor="#000000")
        self.metal_entry_4.configure(selectbackground="#d9d9d9")
        self.metal_entry_4.configure(selectforeground="black")

        self.metal_entry_5 = tk.Entry(self.parameter_setting)
        self.metal_entry_5.place(relx=0.155, rely=0.72, height=37, relwidth=0.14)

        self.metal_entry_5.configure(background="#f0f0f0")
        self.metal_entry_5.configure(disabledforeground="#b4b4b4")
        self.metal_entry_5.configure(font="-family {Times New Roman} -size 14")
        self.metal_entry_5.configure(foreground="#000000")
        self.metal_entry_5.configure(highlightcolor="#000000")
        self.metal_entry_5.configure(selectbackground="#d9d9d9")
        self.metal_entry_5.configure(selectforeground="black")

        self.ontime_entry = tk.Entry(self.parameter_setting)
        self.ontime_entry.place(relx=0.465, rely=0.172, height=37, relwidth=0.14)

        self.ontime_entry.configure(background="#f0f0f0")
        self.ontime_entry.configure(disabledforeground="#b4b4b4")
        self.ontime_entry.configure(font="-family {Times New Roman} -size 14")
        self.ontime_entry.configure(foreground="#000000")
        self.ontime_entry.configure(highlightcolor="#000000")
        self.ontime_entry.configure(selectbackground="#d9d9d9")
        self.ontime_entry.configure(selectforeground="black")

        self.offtime_entry = tk.Entry(self.parameter_setting)
        self.offtime_entry.place(relx=0.465, rely=0.309, height=37, relwidth=0.14)
        self.offtime_entry.configure(background="#f0f0f0")
        self.offtime_entry.configure(disabledforeground="#b4b4b4")
        self.offtime_entry.configure(font="-family {Times New Roman} -size 14")
        self.offtime_entry.configure(foreground="#000000")
        self.offtime_entry.configure(highlightcolor="#000000")
        self.offtime_entry.configure(selectbackground="#d9d9d9")
        self.offtime_entry.configure(selectforeground="black")

        self.cycle_entry = tk.Entry(self.parameter_setting)
        self.cycle_entry.place(relx=0.465, rely=0.446, height=37, relwidth=0.14)
        self.cycle_entry.configure(background="#f0f0f0")
        self.cycle_entry.configure(disabledforeground="#b4b4b4")
        self.cycle_entry.configure(font="-family {Times New Roman} -size 14")
        self.cycle_entry.configure(foreground="#000000")
        self.cycle_entry.configure(highlightcolor="#000000")
        self.cycle_entry.configure(selectbackground="#d9d9d9")
        self.cycle_entry.configure(selectforeground="black")

        self.spectra_interval_entry = tk.Entry(self.parameter_setting)
        self.spectra_interval_entry.place(relx=0.465, rely=0.72, height=37, relwidth=0.14)
        self.spectra_interval_entry.configure(background="#f0f0f0")
        self.spectra_interval_entry.configure(disabledforeground="#b4b4b4")
        self.spectra_interval_entry.configure(font="-family {Times New Roman} -size 14")
        self.spectra_interval_entry.configure(foreground="#000000")
        self.spectra_interval_entry.configure(highlightcolor="#000000")
        self.spectra_interval_entry.configure(selectbackground="#d9d9d9")
        self.spectra_interval_entry.configure(selectforeground="black")

        self.integration_time_entry = tk.Entry(self.parameter_setting)
        self.integration_time_entry.place(relx=0.465, rely=0.583, height=37, relwidth=0.14)
        self.integration_time_entry.configure(background="#f0f0f0")
        self.integration_time_entry.configure(disabledforeground="#b4b4b4")
        self.integration_time_entry.configure(font="-family {Times New Roman} -size 14")
        self.integration_time_entry.configure(foreground="#000000")
        self.integration_time_entry.configure(highlightcolor="#000000")
        self.integration_time_entry.configure(selectbackground="#d9d9d9")
        self.integration_time_entry.configure(selectforeground="black")

        self.conductivity_entry = tk.Entry(self.parameter_setting)
        self.conductivity_entry.place(relx=0.795, rely=0.309, height=37, relwidth=0.14)
        self.conductivity_entry.configure(background="#f0f0f0")
        self.conductivity_entry.configure(disabledforeground="#b4b4b4")
        self.conductivity_entry.configure(font="-family {Times New Roman} -size 14")
        self.conductivity_entry.configure(foreground="#000000")
        self.conductivity_entry.configure(highlightcolor="#000000")
        self.conductivity_entry.configure(selectbackground="#d9d9d9")
        self.conductivity_entry.configure(selectforeground="black")

        self.voltage_entry = tk.Entry(self.parameter_setting)
        self.voltage_entry.place(relx=0.795, rely=0.172, height=37, relwidth=0.14)
        self.voltage_entry.configure(background="#f0f0f0")
        self.voltage_entry.configure(disabledforeground="#b4b4b4")
        self.voltage_entry.configure(font="-family {Times New Roman} -size 14")
        self.voltage_entry.configure(foreground="#000000")
        self.voltage_entry.configure(highlightcolor="#000000")
        self.voltage_entry.configure(selectbackground="#d9d9d9")
        self.voltage_entry.configure(selectforeground="black")

        self.loop_entry = tk.Entry(self.parameter_setting)
        self.loop_entry.place(relx=0.795, rely=0.446, height=37, relwidth=0.14)
        self.loop_entry.configure(background="#f0f0f0")
        self.loop_entry.configure(disabledforeground="#b4b4b4")
        self.loop_entry.configure(font="-family {Times New Roman} -size 14")
        self.loop_entry.configure(foreground="#000000")
        self.loop_entry.configure(highlightcolor="#000000")
        self.loop_entry.configure(selectbackground="#d9d9d9")
        self.loop_entry.configure(selectforeground="black")

        self.save_path_text = tk.Entry(self.parameter_setting)
        self.save_path_text.place(relx=0.203, rely=0.035, height=30, relwidth=0.391)
        self.save_path_text.configure(background="white")
        self.save_path_text.configure(disabledforeground="#b4b4b4")
        self.save_path_text.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.save_path_text.configure(highlightcolor="#000000")
        self.save_path_text.configure(selectbackground="#d9d9d9")
        self.save_path_text.configure(selectforeground="black")
        self.save_path_text.insert(0, self.save_path)

        self.raspberrypi_controll_functions = control_gui_support.RaspberryPiController(self)
        self.start_button = tk.Button(self.parameter_setting)
        self.start_button.place(relx=0.824, rely=0.669, height=66, width=108)
        self.start_button.configure(activebackground="#d9d9d9")
        self.start_button.configure(activeforeground="black")
        self.start_button.configure(command=self.raspberrypi_controll_functions.start)
        self.start_button.configure(disabledforeground="#b4b4b4")
        self.start_button.configure(font="-family {Times New Roman} -size 18")
        self.start_button.configure(foreground="#000000")
        self.start_button.configure(highlightcolor="#000000")
        self.start_button.configure(text="""Start""")

        self.stop_button = tk.Button(self.parameter_setting)
        self.stop_button.place(relx=0.7, rely=0.669, height=66, width=108)
        self.stop_button.configure(activebackground="#d9d9d9")
        self.stop_button.configure(activeforeground="black")
        self.stop_button.configure(command=self.raspberrypi_controll_functions.close_ui)
        self.stop_button.configure(disabledforeground="#b4b4b4")
        self.stop_button.configure(font="-family {Times New Roman} -size 18")
        self.stop_button.configure(foreground="#000000")
        self.stop_button.configure(highlightcolor="#000000")
        self.stop_button.configure(text="Close UI", font="-family {Times New Roman} -size 13")

        self.combobox_var_parameter = tk.StringVar()
        self.parameter_combobox = ttk.Combobox(self.parameter_setting)
        self.parameter_combobox.place(relx=0.61, rely=0.035, relheight=0.053, relwidth=0.348)
        self.parameter_combobox.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.parameter_combobox.configure(textvariable=self.combobox_var_parameter)
        self.parameter_combobox.bind(
            "<<ComboboxSelected>>", self.raspberrypi_controll_functions.update_entries_from_combobox
        )

        self.select_mode_functions = control_gui_support.SelectModeFunctions(self)
        self.back_button = tk.Button(
            self.parameter_setting,
            command=lambda: self.select_mode_functions.back_to_mode_select(self.top, save_path),
        )
        self.back_button.place(relx=0.029, rely=0.018, height=46, width=48)
        self.back_button.configure(activebackground="#d9d9d9")
        self.back_button.configure(activeforeground="black")
        self.back_button.configure(disabledforeground="#b4b4b4")
        self.back_button.configure(font="-family {Microsoft JhengHei UI} -size 16")
        self.back_button.configure(foreground="#000000")
        self.back_button.configure(highlightcolor="#000000")
        self.back_button.configure(text="""↩""")

        self.wash_button = tk.Button(
            self.parameter_setting, command=self.raspberrypi_controll_functions.wash
        )
        self.wash_button.place(relx=0.087, rely=0.018, height=46, width=48)
        self.wash_button.configure(activebackground="#d9d9d9")
        self.wash_button.configure(activeforeground="black")
        self.wash_button.configure(disabledforeground="#b4b4b4")
        self.wash_button.configure(font="-family {Microsoft JhengHei UI} -size 9")
        self.wash_button.configure(foreground="#000000")
        self.wash_button.configure(highlightcolor="#000000")
        self.wash_button.configure(text="""Wash""")
        self.wash_button.place_forget()  # No washing operation exists in this legacy controller.

        self.Button3 = tk.Button(self.parameter_setting)
        self.Button3.place(relx=0.145, rely=0.018, height=46, width=48)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(disabledforeground="#b4b4b4")
        self.Button3.configure(font="-family {Microsoft JhengHei UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text="""Button""")
        self.Button3.place_forget()  # Unassigned designer control; not an implemented operation.

        self.savepath_button = tk.Button(self.parameter_setting)
        self.savepath_button.place(relx=0.571, rely=0.035, height=30, width=28)
        self.savepath_button.configure(activebackground="#d9d9d9")
        self.savepath_button.configure(activeforeground="black")
        self.savepath_button.configure(disabledforeground="#b4b4b4")
        self.savepath_button.configure(foreground="#000000")
        self.savepath_button.configure(highlightcolor="#000000")
        self.savepath_button.configure(text="""...""")
        self.savepath_button.configure(command=self.raspberrypi_controll_functions.change_save_path)

        self.spectrum_label = tk.Label(self.result)
        self.spectrum_label.place(relx=0.232, rely=0.071, height=50, width=103)
        self.spectrum_label.configure(activebackground="#d9d9d9")
        self.spectrum_label.configure(activeforeground="black")
        self.spectrum_label.configure(anchor="w")
        self.spectrum_label.configure(compound="left")
        self.spectrum_label.configure(disabledforeground="#b4b4b4")
        self.spectrum_label.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.spectrum_label.configure(foreground="#000000")
        self.spectrum_label.configure(highlightcolor="#000000")
        self.spectrum_label.configure(text="""Spectrum""")

        self.time_series_label = tk.Label(self.result)
        self.time_series_label.place(relx=0.678, rely=0.071, height=50, width=141)
        self.time_series_label.configure(activebackground="#d9d9d9")
        self.time_series_label.configure(activeforeground="black")
        self.time_series_label.configure(anchor="w")
        self.time_series_label.configure(compound="left")
        self.time_series_label.configure(disabledforeground="#b4b4b4")
        self.time_series_label.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.time_series_label.configure(foreground="#000000")
        self.time_series_label.configure(highlightcolor="#000000")
        self.time_series_label.configure(text="""Time Series""")

        self.combobox_var_time = tk.StringVar()
        self.time_series_list = ttk.Combobox(self.result)
        self.time_series_list.place(relx=0.513, rely=0.142, relheight=0.055, relwidth=0.439)
        self.time_series_list.configure(textvariable=self.combobox_var_time)
        self.time_series_list.configure(takefocus="")
        self.time_series_list.bind(
            "<<ComboboxSelected>>",
            self.raspberrypi_controll_functions.time_series_wavelength_change,
        )
        self.time_series_list.bind(
            "<Return>", self.raspberrypi_controll_functions.time_series_wavelength_change
        )

        self.combobox_var_spectrum = tk.StringVar()
        self.spectrum_combobox = ttk.Combobox(self.result)
        self.spectrum_combobox.place(relx=0.048, rely=0.142, relheight=0.055, relwidth=0.446)
        self.spectrum_combobox.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.spectrum_combobox.configure(textvariable=self.combobox_var_spectrum)
        self.spectrum_combobox.bind(
            "<<ComboboxSelected>>", self.raspberrypi_controll_functions.update_plot
        )

        self.time_series = tk.Frame(self.result)
        self.time_series.place(relx=0.513, rely=0.213, relheight=0.571, relwidth=0.439)
        self.time_series.config(borderwidth="2", relief="ridge")
        self.time_series.config(background="white")

        self.spectrum = tk.Frame(self.result)
        self.spectrum.place(relx=0.048, rely=0.213, relheight=0.571, relwidth=0.446)
        self.spectrum.config(borderwidth="2", relief="ridge")
        self.spectrum.config(background="white")

        self.average_var = tk.IntVar()
        self.average_var.set(0)
        self.average = ttk.Checkbutton(self.result, variable=self.average_var)
        self.average.place(relx=0.42, rely=0.086, relwidth=0.076, relheight=0.0, height=31)
        self.average.configure(takefocus="")
        self.average.configure(text="""Average""")
        self.average.configure(compound="left")
        self.average.configure(command=self.raspberrypi_controll_functions.update_plot)

        self.combobox_var_background = tk.StringVar()
        self.background_list = ttk.Combobox(self.result)
        self.background_list.place(relx=0.678, rely=0.018, relheight=0.055, relwidth=0.129)
        self.background_list.configure(font="-family {Microsoft JhengHei UI} -size 11")
        self.background_list.configure(textvariable=self.combobox_var_background)
        # =============================================================================
        #         self.background_list.bind("<<ComboboxSelected>>", self.raspberrypi_controll_functions.time_series_wavelength_change)
        #         self.background_list.bind("<Return>", self.raspberrypi_controll_functions.time_series_wavelength_change)
        # =============================================================================
        self.background_list.set("<Background>")

        self.combobox_var_normalize = tk.StringVar()
        self.normalize_list = ttk.Combobox(self.result)
        self.normalize_list.place(relx=0.813, rely=0.018, relheight=0.055, relwidth=0.136)
        self.normalize_list.configure(font="-family {Microsoft JhengHei UI} -size 11")
        self.normalize_list.configure(textvariable=self.combobox_var_normalize)
        self.normalize_list.bind(
            "<<ComboboxSelected>>", self.raspberrypi_controll_functions.normalize_wavelength_change
        )
        self.normalize_list.bind(
            "<Return>", self.raspberrypi_controll_functions.normalize_wavelength_change
        )
        self.normalize_list.set("<Normalize>")

        self.console_text = tk.Text(self.top)
        self.console_text.place(relx=0.048, rely=0.84, relheight=0.108, relwidth=0.88)
        self.console_text.configure(background="#f0f0f0")
        self.console_text.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.console_text.configure(highlightcolor="#000000")
        self.console_text.configure(selectbackground="#a0a0a0")
        self.console_text.configure(selectforeground="black")
        self.console_text.configure(wrap="word")
        self.console_text.configure(state=tk.DISABLED)

        self.console_scrollbar = tk.Scrollbar(self.top)
        self.console_scrollbar.place(relx=0.911, rely=0.839, relheight=0.113, relwidth=0.02)
        self.console_scrollbar.configure(activebackground="#d9d9d9")

        self.console_text.configure(yscrollcommand=self.console_scrollbar.set)

        queue = Queue()
        sys.stdout = control_gui_support.StdoutRedirector(self.console_text, queue)
        self.console_text.after(100, sys.stdout.process_queue)


# =============================================================================
#     def embed_pyqt_window(self):
#         # Create a PyQt application instance
#         self.app_pyqt = QApplication.instance()
#         if self.app_pyqt is None:
#             self.app_pyqt = QApplication(sys.argv)
#
#         # Create the PyQt main window
#         self.spectrum_processor_window = MainWindow()
#
#         # Read the native window ID
#         window_id = int(self.spectrum_processor_window.winId())
#
#         # Embed the PyQt window in a Tkinter frame with QWidget.createWindowContainer
#         self.qt_container = QWidget.createWindowContainer(QWindow.fromWinId(window_id), self.pyqt_embed_frame)
#         self.qt_container.setMinimumSize(self.spectrum_processor_window.minimumSize())
#         self.qt_container.setMaximumSize(self.spectrum_processor_window.maximumSize())
#         self.qt_container.resize(self.spectrum_processor_window.size())
#         self.qt_container.show()
#
#         # Display the PyQt window
#         self.spectrum_processor_window.show()
# =============================================================================


class Toplevel2:
    def __init__(self, top=None, save_path=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""

        top.geometry("575x266+773+338")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("Mode Selection")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.select_mode_functions = control_gui_support.SelectModeFunctions(
            self
        )  # Create the mode-selection controller

        self.menubar = tk.Menu(top, font="TkMenuFont", bg="#f0f0f0", fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Mode1 = tk.Button(self.top, command=lambda: self.select_mode_functions.select_mode(1))
        self.Mode1.place(relx=0.122, rely=0.15, height=56, width=118)
        self.Mode1.configure(activebackground="#d9d9d9")
        self.Mode1.configure(activeforeground="black")
        self.Mode1.configure(disabledforeground="#b4b4b4")
        self.Mode1.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Mode1.configure(foreground="#000000")
        self.Mode1.configure(highlightcolor="#000000")
        self.Mode1.configure(text="""Mode1""")

        self.Mode2 = tk.Button(self.top, command=lambda: self.select_mode_functions.select_mode(2))
        self.Mode2.place(relx=0.4, rely=0.15, height=56, width=118)
        self.Mode2.configure(activebackground="#d9d9d9")
        self.Mode2.configure(activeforeground="black")
        self.Mode2.configure(disabledforeground="#b4b4b4")
        self.Mode2.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Mode2.configure(foreground="#000000")
        self.Mode2.configure(highlightcolor="#000000")
        self.Mode2.configure(text="""Mode2""")

        self.Mode3 = tk.Button(self.top, command=lambda: self.select_mode_functions.select_mode(3))
        self.Mode3.place(relx=0.678, rely=0.15, height=56, width=118)
        self.Mode3.configure(activebackground="#d9d9d9")
        self.Mode3.configure(activeforeground="black")
        self.Mode3.configure(disabledforeground="#b4b4b4")
        self.Mode3.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Mode3.configure(foreground="#000000")
        self.Mode3.configure(highlightcolor="#000000")
        self.Mode3.configure(text="Unavailable", state=tk.DISABLED)
        self.Mode3.place_forget()  # Only raw and background-subtracted acquisition are implemented.

        self.ok_button = tk.Button(self.top, command=self.select_mode_functions.proceed)
        self.ok_button.place(relx=0.435, rely=0.752, height=36, width=78)
        self.ok_button.configure(activebackground="#d9d9d9")
        self.ok_button.configure(activeforeground="black")
        self.ok_button.configure(disabledforeground="#b4b4b4")
        self.ok_button.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.ok_button.configure(foreground="#000000")
        self.ok_button.configure(highlightcolor="#000000")
        self.ok_button.configure(text="""OK""")
        self.ok_button.configure(state=tk.DISABLED)

        self.save_path_button = tk.Button(
            self.top, command=self.select_mode_functions.select_folder
        )
        self.save_path_button.place(relx=0.052, rely=0.492, height=36, width=88)
        self.save_path_button.configure(activebackground="#d9d9d9")
        self.save_path_button.configure(activeforeground="black")
        self.save_path_button.configure(disabledforeground="#b4b4b4")
        self.save_path_button.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.save_path_button.configure(foreground="#000000")
        self.save_path_button.configure(highlightcolor="#000000")
        self.save_path_button.configure(text="""Save Path""")

        self.save_path_entry = tk.Entry(self.top)
        self.save_path_entry.place(relx=0.209, rely=0.489, height=37, relwidth=0.737)
        self.save_path_entry.configure(background="#f0f0f0")
        self.save_path_entry.configure(disabledforeground="#b4b4b4")
        self.save_path_entry.configure(font="-family {Microsoft JhengHei UI} -size 12")
        self.save_path_entry.configure(foreground="#000000")
        self.save_path_entry.configure(highlightcolor="#000000")
        self.save_path_entry.configure(selectbackground="#d9d9d9")
        self.save_path_entry.configure(selectforeground="black")
        if save_path:
            self.save_path_entry.insert(0, save_path)


def start_up():
    control_gui_support.main()


if __name__ == "__main__":
    control_gui_support.main()
