#!/usr/bin/env python3
"""Generate firmware/Arduino/hw_config.h from config/hardware.yaml.

Pin assignments and conversion settings are shared by firmware, backend, and
frontend through one configuration file.

    python tools/gen_firmware_config.py          # Generate the header.
    python tools/gen_firmware_config.py --check  # Check freshness for CI.

After changing pin assignments, regenerate the header, upload
firmware/Arduino/Arduino.ino with the Arduino IDE, and restart the backend.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.config import load_config  # noqa: E402

HEADER = ROOT / "firmware" / "Arduino" / "hw_config.h"


def render(cfg: dict) -> str:
    motors = cfg["motors"]
    groups = motors["groups"]
    if len(groups) != 2:
        raise SystemExit("Firmware requires exactly two driver groups in motors.groups")

    ids = [ch["id"] for g in groups for ch in g["channels"]]
    pins = [ch["pin"] for g in groups for ch in g["channels"]]
    if ids != pins:
        raise SystemExit("Firmware maps motor n to D<n>; each channel id must equal its pin")
    if ids != list(range(min(ids), max(ids) + 1)):
        raise SystemExit("Motor IDs must be consecutive, for example 2-9")

    valves = cfg["valves"]["channels"]
    valve_links = {
        int(link["motor"]): int(link["valve"])
        for link in cfg["valves"]["motor_links"]
    }
    motor_valves = [valve_links.get(motor, 0) for motor in ids]
    cleaning = cfg["cleaning"]

    def motor_ppm(motor_id: int) -> float:
        for group in groups:
            for channel in group["channels"]:
                if int(channel["id"]) == motor_id:
                    return float(channel.get("pulses_per_ml", motors["pulses_per_ml"]))
        raise SystemExit(f"Cleaning motor {motor_id} is not configured")

    clean_flow = float(cleaning["flow_ml_min"])
    clean_water_sps = max(
        1, round(clean_flow * motor_ppm(int(cleaning["water_motor"])) / 60.0))
    clean_out_sps = max(
        1, round(clean_flow * motor_ppm(int(cleaning["out_motor"])) / 60.0))
    pump = cfg["syringe_pump"]
    scale = cfg["scale"]
    mb = scale["modbus"]
    a, b = groups[0]["driver"], groups[1]["driver"]

    lines = [
        "// ===================================================================",
        "//  hw_config.h — Generated by tools/gen_firmware_config.py; do not edit manually",
        "//  Source: config/hardware.yaml",
        f"//  {cfg['meta']['name']} — {cfg['meta']['description']}",
        "// ===================================================================",
        "#ifndef HW_CONFIG_H",
        "#define HW_CONFIG_H",
        "",
        "// ---------- Two DM542J drivers ----------",
        f"#define PUL1 {a['pul']}",
        f"#define DIR1 {a['dir']}",
        f"#define ENA1 {a['ena']}",
        f"#define PUL2 {b['pul']}",
        f"#define DIR2 {b['dir']}",
        f"#define ENA2 {b['ena']}",
        "",
        "// ---------- Relays: motor n is controlled by D<n> ----------",
        f"#define FIRST_MOTOR {min(ids)}",
        f"#define LAST_MOTOR  {max(ids)}",
        f"#define GROUP_B_FIRST {groups[1]['channels'][0]['id']}",
        "",
        f"#define MAX_SPS   {float(motors['max_sps']):.1f}",
        f"#define SETTLE_MS {int(motors['driver_settle_ms'])}",
        "",
        "// ---------- Volume conversions used by the interface ----------",
        f"#define PULSES_PER_ML   {float(motors['pulses_per_ml']):.6f}F",
        f"#define PULSES_PER_REV  {int(motors['pulses_per_rev'])}L",
        f"#define MAX_FLOW_UL_MIN {int(float(motors['max_flow_ml_min']) * 1000)}L",
        "",
        "// ---------- Cleaning: water intake, simultaneous operation, then OUT drainage ----------",
        f"#define CLEAN_WATER_MOTOR {int(cleaning['water_motor'])}",
        f"#define CLEAN_OUT_MOTOR {int(cleaning['out_motor'])}",
        f"#define CLEAN_WATER_SPS {clean_water_sps}.0F",
        f"#define CLEAN_OUT_SPS {clean_out_sps}.0F",
        f"#define CLEAN_WATER_LEAD_MS {round(float(cleaning['water_lead_s']) * 1000)}UL",
        f"#define CLEAN_OVERLAP_MS {round(float(cleaning['overlap_s']) * 1000)}UL",
        f"#define CLEAN_OUT_TAIL_MS {round(float(cleaning['out_tail_s']) * 1000)}UL",
        "",
        "// ---------- Solenoid valves ----------",
        f"#define NUM_VALVES {len(valves)}",
        "#define VALVE_PIN_LIST { " + ", ".join(str(v["pin"]) for v in valves) + " }",
        "#define MOTOR_VALVE_LIST { " + ", ".join(str(v) for v in motor_valves) + " }",
        f"#define VALVE_OPEN_BEFORE_MS {int(cfg['valves']['open_before_ms'])}UL",
        f"#define VALVE_CLOSE_AFTER_MS {int(cfg['valves']['close_after_ms'])}UL",
        "",
        "// ---------- Syringe pump ----------",
        f"#define PUMP_SERIAL {pump['serial']}          // TX{pump['serial'][-1]}"
        f"=D{pump['tx_pin']}, RX{pump['serial'][-1]}=D{pump['rx_pin']}",
        f"#define PUMP_BAUD {int(pump['baud'])}UL",
        f"#define PUMP_ADDR {int(pump['address'])}",
        f"#define PUMP_FULL_STROKE {int(pump['full_stroke_steps'])}L",
        f"#define PUMP_DEFAULT_SYRINGE_UL {int(pump['default_syringe_ul'])}L",
        "",
        "// ---------- Scale transmitter ----------",
        f"#define SCALE_SERIAL {scale['serial']}         // TX{scale['serial'][-1]}"
        f"=D{scale['tx_pin']}, RX{scale['serial'][-1]}=D{scale['rx_pin']}",
        f"#define SCALE_DE_PIN {int(scale['de_pin'])}",
        f"#define SCALE_STREAM_HZ {int(scale['stream_hz'])}",
        f"#define SCALE_AVG_SAMPLES {int(scale['average_samples'])}",
        f"#define SCALE_STABLE_G {float(scale['stable_threshold_g']):.6f}F",
        f"#define SCALE_BAUD {int(mb['baud'])}L",
        f"#define SCALE_ADDR {int(mb['address'])}",
        f"#define SCALE_FUNC {int(mb['function_code'])}",
        f"#define SCALE_REG  {int(mb['register'])}",
        f"#define SCALE_FMT  {int(mb['format'])}",
        "",
        "#endif  // HW_CONFIG_H",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Check without writing; exit 1 if the generated header is stale")
    args = ap.parse_args()

    text = render(load_config())
    current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""

    if args.check:
        if current == text:
            print("hw_config.h matches hardware.yaml")
            return 0
        print("hw_config.h is stale; run python tools/gen_firmware_config.py")
        return 1

    if current == text:
        print("hw_config.h is up to date; no changes made")
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(text, encoding="utf-8")
    print(f"Wrote {HEADER.relative_to(ROOT)}; upload the updated firmware to the Arduino")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
