from lab_config import load_settings
import shlex

#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 10, 2025 10:05:57 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import messagebox
import time
import os
from tkinter import filedialog
import json
import paramiko
from scp import SCPClient
from threading import Thread
import queue
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
from matplotlib.colors import to_hex
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib
import matplotlib.colors as mcolors
from matplotlib.backends.backend_tkagg import NavigationToolbar2Tk as NavigationToolbar
import pandas as pd
import numpy as np

import control_gui

debug = False


def main(*args):
    """Main entry point for the application."""
    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
    _top2 = root
    _w2 = control_gui.Toplevel2(_top2)
    root.mainloop()


class SelectModeFunctions:
    def __init__(self, top):
        self.top = top
        self.selected_mode = None

    def select_mode(self, mode):
        self.selected_mode = mode
        self.reset_button_colors()
        if mode == 1:
            self.top.Mode1.configure(bg="lightblue")
        elif mode == 2:
            self.top.Mode2.configure(bg="lightblue")
        else:
            self.top.Mode3.configure(bg="lightblue")
        self.update_ok_button_state()

    def reset_button_colors(self):
        self.top.Mode1.configure(bg="SystemButtonFace")
        self.top.Mode2.configure(bg="SystemButtonFace")
        self.top.Mode3.configure(bg="SystemButtonFace")

    def update_ok_button_state(self):
        if self.selected_mode is not None and self.top.save_path_entry.get():
            self.top.ok_button.configure(state=tk.NORMAL)
        else:
            self.top.ok_button.configure(state=tk.DISABLED)

    def proceed(self):
        folder_path = self.top.save_path_entry.get()
        try:
            os.makedirs(folder_path, exist_ok=True)
        except Exception as e:
            print(f"Error creating directory: {e}")

        if self.selected_mode == 1:
            self.show_mode1(self.top.top, folder_path)
        elif self.selected_mode == 2:
            self.show_mode2(self.top.top, folder_path)
        elif self.selected_mode == 3:
            self.show_mode3(self.top.top, folder_path)

    def select_folder(self):
        folder_selected = filedialog.askdirectory()
        if folder_selected:
            self.top.save_path_entry.delete(0, tk.END)
            self.top.save_path_entry.insert(0, folder_selected)
            self.update_ok_button_state()

    def show_mode1(self, mode_select_window, directory_name):
        mode_select_window.destroy()
        root = tk.Tk()
        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        _top1 = root
        _w1 = control_gui.Toplevel1(
            directory_name, self.selected_mode, _top1
        )  # Pass the save path and selected mode
        _w1.time_series_list.config(values=load_time_series_config())
        _w1.normalize_list.config(values=load_normalize_config())

    def show_mode2(self, mode_select_window, directory_name):
        mode_select_window.destroy()
        root = tk.Tk()
        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        _top1 = root
        _w1 = control_gui.Toplevel1(
            directory_name, self.selected_mode, _top1
        )  # Pass the save path and selected mode
        _w1.time_series_list.config(values=load_time_series_config())
        _w1.normalize_list.config(values=load_normalize_config())

    def show_mode3(self, mode_select_window, directory_name):
        0
        # mode_select_window.destroy()

    def back_to_mode_select(self, main_mode_window, save_path):
        main_mode_window.destroy()  # Close the acquisition window
        root = tk.Tk()
        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        _top2 = root
        _w2 = control_gui.Toplevel2(_top2, save_path)  # Reopen the mode-selection window


class RaspberryPiController:
    def __init__(self, w1):
        self.w1 = w1
        self.parameter_history = []
        self.load_config()
        self.file_path_list = []  # Initialize before first use
        self.queue = queue.Queue()
        self.current_thread = None  # Store the thread object
        self.latest_file_path, self.parameter_dict = self.load_latest_file_path()
        self.zoom_ax = None
        self.stop_file_remote = os.path.dirname(self.pi_python_file) + "/stop_rpi_control"
        self.is_wash = False
        self.stop = False

    def get_result_from_pi(self):
        try:
            import paramiko
            from scp import SCPClient
            import os
            import sys
            import time
            import tkinter.messagebox as messagebox

            print("[INFO] Connecting to the Raspberry Pi and downloading the latest acquisition...")

            client = paramiko.SSHClient()
            client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            client.connect(
                self.pi_address, username=self.pi_user, password=self.pi_password, timeout=3
            )

            # Find the latest date-organized acquisition directory
            command = "ls -td " + shlex.quote(self.pi_data_dir.rstrip("/")) + "/*/*/ | head -n 1"
            stdin, stdout, stderr = client.exec_command(command)
            latest_folder = stdout.read().decode().strip()
            print(f"[DEBUG] Latest acquisition directory: {latest_folder}")

            if not latest_folder:
                raise Exception(
                    "No acquisition directory was found. Spectra may not have been generated yet."
                )

            # Copy the complete acquisition directory through SCP
            scp = SCPClient(client.get_transport())
            local_path = self.local_file  # Destination directory selected in the GUI
            scp.get(latest_folder, recursive=True, local_path=local_path)

            # Collect all spectrum text-file paths from the downloaded directory
            saved_folder_name = os.path.basename(os.path.normpath(latest_folder))
            full_local_folder = os.path.join(local_path, saved_folder_name)

            self.file_path_list = []
            for root, dirs, files in os.walk(full_local_folder):
                for file in files:
                    if file.endswith(".txt"):
                        self.file_path_list.append(os.path.join(root, file))

            if not self.file_path_list:
                print("[WARNING] No spectrum text files were downloaded")
            else:
                print(f"[INFO] Retrieved {len(self.file_path_list)} spectra")

            self.latest_file_path[self.counted_param_str] = self.file_path_list
            self.save_latest_file_path()

            scp.close()
            client.close()

        except Exception as e:
            print(f"[ERROR] Acquisition download failed: {e}")
            sys.stdout.flush()
            messagebox.showerror("Error", f"File transfer failed: \n{str(e)}")

    def load_config(self):
        settings = load_settings()
        self.pi_user = settings["pi_user"]
        self.pi_address = settings["pi_address"]
        self.pi_python_file = settings["pi_python_file"]
        self.pi_password = settings["pi_password"] or None
        self.pi_data_dir = settings["pi_data_dir"]

    def change_save_path(self):
        folder_selected = filedialog.askdirectory()
        if folder_selected:
            self.w1.save_path_text.delete(0, tk.END)
            self.w1.save_path_text.insert(0, folder_selected)

    def start(self, *args):
        if not debug:
            if self.w1:
                self.w1.start_button.config(state=tk.DISABLED)
                self.w1.stop_button.config(state=tk.NORMAL)
                entries = {
                    "Ontime": (self.w1.ontime_entry, float),
                    "Offtime": (self.w1.offtime_entry, int),
                    "Cycle": (self.w1.cycle_entry, int),
                    "Integration Time": (self.w1.integration_time_entry, int),
                    "Spectra Interval": (self.w1.spectra_interval_entry, int),
                    "Voltage": (self.w1.voltage_entry, int),
                    "Conductivity": (self.w1.conductivity_entry, int),
                    "Loopnum": (self.w1.loop_entry, int),
                }

                metal_entries = {
                    "Metal1": (self.w1.metal_entry_1, float),
                    "Metal2": (self.w1.metal_entry_2, float),
                    "Metal3": (self.w1.metal_entry_3, float),
                    "Metal4": (self.w1.metal_entry_4, float),
                    "Metal5": (self.w1.metal_entry_5, float),
                }

                self.values = {}
                self.errors = []

                for name, (entry, value_type) in entries.items():
                    try:
                        self.values[name] = value_type(entry.get())
                    except:
                        self.errors.append(name)

                for name, (entry, value_type) in metal_entries.items():
                    try:
                        entry_value = entry.get()
                        if entry_value == "":
                            self.values[name] = 0.0
                        else:
                            self.values[name] = value_type(entry_value)
                    except:
                        self.errors.append(name)

                # Store the selected acquisition mode
                selected_mode = self.w1.select_mode
                if selected_mode is not None:
                    self.values["Selected Mode"] = selected_mode
                else:
                    self.errors.append("Selected Mode")

                self.values["Wash"] = self.is_wash

                if self.errors:
                    messagebox.showerror(
                        "Error",
                        "Invalid values in the following fields: \n" + "\n".join(self.errors),
                    )
                    self.w1.start_button.config(state=tk.NORMAL)
                    self.w1.stop_button.config(state=tk.DISABLED)
                    return None

                else:
                    self.update_parameter_history()  # Update the parameter-history menu
                    self.local_file = self.w1.save_path_text.get()
                    os.makedirs(
                        self.local_file, exist_ok=True
                    )  # Ensure that the local destination directory exists

                    print(
                        f"{self.count} =============================\nAcquisition is running on the Raspberry Pi"
                    )
                    thread = Thread(target=self.run_pi_commands)
                    thread.start()
                    self.queue.put(thread)  # Queue the thread for status monitoring
                    self.end_of_pi()  # Start monitoring the acquisition thread
                    return self.values
        else:
            self.local_file = self.w1.save_path_text.get()
            file_path_list = []
            for filename in os.listdir(self.local_file):
                if filename.endswith(".txt"):
                    file_path = os.path.join(self.local_file, filename)
                    file_path_list.append(file_path)
            self.latest_file_path["123"] = file_path_list
            self.counted_param_str = "123"
            self.nor_point_index = None
            self.w1.spectrum_combobox.set("123")
            if self.w1.spectrum_combobox.get():
                self.update_plot()

    def run_pi_commands(self):
        try:
            if self.send_to_pi(self.values) and not self.stop:
                sys.stdout.write("Starting file transfer\n")
                sys.stdout.flush()
                self.get_result_from_pi()
        finally:
            self.queue.put("thread_finished")

    def update_parameter_history(self):
        # Serialize the current parameters and append them to the history
        # Parameter serialization order
        ordered_keys = [
            "Voltage",
            "Ontime",
            "Offtime",
            "Cycle",
            "Conductivity",
            "Metal1",
            "Metal2",
            "Metal3",
            "Metal4",
            "Metal5",
        ]
        ordered_values = []
        for key in ordered_keys:
            if key in self.values:
                ordered_values.append(str(self.values[key]))
        param_str = "_".join(ordered_values)
        self.count = len(self.parameter_history) + 1
        self.counted_param_str = format_title(f"({self.count}) {param_str}")
        self.parameter_history.insert(0, self.counted_param_str)
        self.w1.parameter_combobox["values"] = self.parameter_history
        self.w1.spectrum_combobox["values"] = self.parameter_history
        self.w1.spectrum_combobox.set(self.counted_param_str)
        self.parameter_dict[self.counted_param_str] = self.values

    def update_entries_from_combobox(self, event):
        parameter = self.parameter_dict[self.w1.parameter_combobox.get()]
        entries = {
            self.w1.ontime_entry: parameter["Ontime"],
            self.w1.offtime_entry: parameter["Offtime"],
            self.w1.cycle_entry: parameter["Cycle"],
            self.w1.integration_time_entry: parameter["Integration Time"],
            self.w1.spectra_interval_entry: parameter["Spectra Interval"],
            self.w1.voltage_entry: parameter["Voltage"],
            self.w1.conductivity_entry: parameter["Conductivity"],
            self.w1.loop_entry: parameter["Loopnum"],
            self.w1.metal_entry_1: parameter["Metal1"],
            self.w1.metal_entry_2: parameter["Metal2"],
            self.w1.metal_entry_3: parameter["Metal3"],
            self.w1.metal_entry_4: parameter["Metal4"],
            self.w1.metal_entry_5: parameter["Metal5"],
        }

        for entry, value in zip(entries.keys(), entries.values()):
            entry.delete(0, tk.END)
            entry.insert(0, value)

    # The effective UART/GPIO sender is defined below.

    def send_to_pi(self, parameter):
        import json, time, sys
        import paramiko
        from tkinter import messagebox

        parameter_json = json.dumps(parameter)
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        try:
            # Open the SSH connection
            client.connect(
                self.pi_address, username=self.pi_user, password=self.pi_password, timeout=3
            )

            # Use the configured remote controller path
            trigger_path = self.pi_python_file
            command = (
                "sudo python3 -u " + shlex.quote(trigger_path) + " " + shlex.quote(parameter_json)
            )

            print(f"[DEBUG] Executing the Raspberry Pi command: {command}")
            sys.stdout.flush()

            # Open an SSH channel
            transport = client.get_transport()
            channel = transport.open_session()
            channel.get_pty()
            channel.exec_command(command)

            stdout_data = ""
            stderr_data = ""

            # Continue reading output until completion
            while (
                not channel.exit_status_ready()
                or channel.recv_ready()
                or channel.recv_stderr_ready()
            ):
                if channel.recv_ready():
                    chunk = channel.recv(4096)
                    if chunk:
                        try:
                            text = chunk.decode("utf-8")
                        except UnicodeDecodeError:
                            text = chunk.decode("latin-1")
                        stdout_data += text
                        sys.stdout.write(text)
                        sys.stdout.flush()
                if channel.recv_stderr_ready():
                    chunk = channel.recv_stderr(4096)
                    if chunk:
                        try:
                            text = chunk.decode("utf-8")
                        except UnicodeDecodeError:
                            text = chunk.decode("latin-1")
                        stderr_data += text
                        sys.stdout.write(text)
                        sys.stdout.flush()
                time.sleep(0.1)

            exit_status = channel.recv_exit_status()
            if exit_status != 0:
                raise RuntimeError(
                    f"Remote controller exited with status {exit_status}. "
                    "Review the acquisition log before retrying."
                )
            return True

        except Exception as e:
            sys.stdout.write(f"Connection or remote execution failed: {str(e)}\n")
            sys.stdout.flush()
            messagebox.showerror(
                "UART/GPIO error", f"Connection or remote execution failed:\n{str(e)}"
            )
            return False

        finally:
            client.close()

    def end_of_pi(self):
        try:
            message = self.queue.get_nowait()
            if isinstance(message, Thread):  # A thread object was queued by start()
                self.current_thread = message  # Store the thread object
            elif message == "thread_finished" and not self.stop:
                if self.file_path_list:
                    self.latest_file_path[self.counted_param_str] = (
                        self.file_path_list
                    )  # Store the acquisition files for this parameter set
                    self.save_latest_file_path()
                    self.w1.start_button.config(state=tk.NORMAL)  # Update the GUI state
                    try:
                        self.selected_condition = self.w1.spectrum_combobox.get()
                        if self.latest_file_path[self.selected_condition]:
                            self.nor_point_index = None
                            self.update_plot()
                        return  # Stop polling
                    except Exception as e:
                        # print(f'Cannot find txt files, {e}')
                        sys.stdout.flush()
            elif message == "thread_finished" and self.stop:
                self.w1.start_button.config(state=tk.NORMAL)
                self.stop = False
                return
        except queue.Empty:
            pass

        if (
            self.current_thread and self.current_thread.is_alive()
        ):  # Continue polling while the thread is active
            self.w1.start_button.after(100, self.end_of_pi)  # Schedule the next status check
        else:
            self.w1.start_button.config(
                state=tk.NORMAL
            )  # Restore the GUI after the thread completes

    def close_ui(self):
        """Close the GUI without writing a remote stop marker."""
        import sys

        try:
            # When the acquisition window exists
            self.w1.top.destroy()
        except AttributeError:
            pass  # The mode-selection window is still active
        try:
            self.top.destroy()
        except AttributeError:
            pass
        sys.exit(0)

    def wash(self):
        self.w1.wash_button.configure(bg="lightblue")
        if self.is_wash:
            self.w1.wash_button.configure(bg="SystemButtonFace")
            self.is_wash = False
        else:
            self.w1.wash_button.configure(bg="lightblue")
            self.is_wash = True

    def plot_spectrum(self):
        result = data_reader(self.latest_file_path[self.selected_condition])
        conditions, data, grouped_conditions = result.Data_transfer()

        # Replace the previous FigureCanvasTkAgg widget
        if hasattr(self, "spectrum_canvas") and self.spectrum_canvas:
            self.spectrum_canvas.get_tk_widget().destroy()

        self.spectrum_fig = Figure(figsize=(4, 4), dpi=100)
        self.spectrum_fig.subplots_adjust(left=0.15, right=0.97, top=0.9, bottom=0.15)
        self.spectrum_ax = self.spectrum_fig.add_subplot(111)

        self.wavelength = data.columns.astype(float)
        avg_spectrum = np.zeros_like(self.wavelength, dtype=float)

        cmap = plt.cm.RdPu
        colors = [
            cmap(0.2 + 0.6 * (i / (len(data)))) for i in range(len(data))
        ]  # Avoid colors that are too light
        colors = [to_hex(c) for c in colors]
        for i in range(len(data)):
            y_data = data.iloc[i].values
            if self.nor_point_index:
                normalization_value = data.iloc[i].values[self.nor_point_index]
                y_data = y_data / normalization_value

            avg_spectrum += y_data
            if self.w1.average_var.get() == 0:
                self.spectrum_ax.plot(self.wavelength, y_data, color=colors[i], label=i + 1)
        if self.w1.average_var.get() == 1:
            self.spectrum_ax.plot(self.wavelength, avg_spectrum / len(data), color="#42A5F5")

        if self.nor_point_index:
            mark_intensity = y_data
            self.spectrum_ax.plot(
                self.wavelength[self.nor_point_index],
                mark_intensity[self.nor_point_index],
                marker="*",
                color="yellow",
                markeredgecolor="black",
                markersize=12,
            )

        title = self.selected_condition
        self.spectrum_ax.set_title(title, fontsize=10)
        self.spectrum_ax.set_xlabel("Wavelength (nm)", fontsize=10)
        self.spectrum_ax.set_ylabel("Intensity (a.u.)", fontsize=10)
        self.spectrum_ax.tick_params(axis="both", labelsize=8)
        (
            self.spectrum_ax.yaxis.set_major_formatter(
                ticker.FuncFormatter(lambda x, pos: f"{int(x/1000)}k")
            )
            if not self.nor_point_index
            else None
        )

        self.spectrum_canvas = FigureCanvasTkAgg(self.spectrum_fig, master=self.w1.spectrum)
        self.spectrum_canvas.draw()
        plot_widget = self.spectrum_canvas.get_tk_widget()
        plot_widget.pack(fill=tk.BOTH, expand=True)  # Place the plotting widget with pack
        self.spectrum_canvas.mpl_connect("button_press_event", self.on_click)
        self.spectrum_canvas.mpl_connect(
            "button_press_event", lambda event: self.spectrum_normalization(event)
        )

        self.click_timer = None

    def plot_time_series(self):
        result = data_reader(self.latest_file_path[self.selected_condition])
        conditions, data, grouped_conditions = result.Data_transfer()

        # Replace the previous FigureCanvasTkAgg widget
        if hasattr(self, "time_canvas") and self.time_canvas:
            self.time_canvas.get_tk_widget().destroy()

        self.time_fig = Figure(figsize=(4, 3), dpi=100)
        self.time_fig.subplots_adjust(left=0.15, right=0.97, top=0.9, bottom=0.15)
        self.time_ax = self.time_fig.add_subplot(111)

        self.wavelength = data.columns.astype(float)
        selected_wavelengths = float(self.w1.time_series_list.get())
        closest_index = ((self.wavelength - selected_wavelengths) ** 2).argmin()

        time_series_data = []
        time_series_index = []
        for i in range(len(data)):
            y_data = data.iloc[i].values
            if self.nor_point_index:
                normalization_value = data.iloc[i].values[self.nor_point_index]
                y_data = y_data / normalization_value
            intensity = y_data[closest_index]
            time_series_data.append(intensity)
            time_series_index.append(i + 1)

        title = self.selected_condition
        self.time_ax.plot(time_series_index, time_series_data, marker="o", color="#42A5F5")
        self.time_ax.set_title(title, fontsize=10)
        self.time_ax.set_xlabel("Data Index", fontsize=10)
        self.time_ax.set_ylabel("Intensity (a.u.)", fontsize=10)
        self.time_ax.tick_params(axis="both", labelsize=8)
        (
            self.time_ax.yaxis.set_major_formatter(
                ticker.FuncFormatter(lambda x, pos: f"{int(x/1000)}k")
            )
            if not self.nor_point_index
            else None
        )

        self.time_canvas = FigureCanvasTkAgg(self.time_fig, master=self.w1.time_series)
        self.time_canvas.draw()
        plot_widget = self.time_canvas.get_tk_widget()
        plot_widget.pack(fill=tk.BOTH, expand=True)  # Place the plotting widget with pack
        self.time_canvas.mpl_connect("button_press_event", lambda event: self.show_zoom_plot(event))

    def on_click(self, event, zoom_ax=None):
        if event.inaxes is not None:
            if event.button == 2:  # Check for a middle-button click
                self.reset_plot(event, zoom_ax)
            elif event.inaxes == self.spectrum_ax:
                if self.click_timer:  # Cancel the existing click timer
                    self.w1.spectrum.after_cancel(self.click_timer)
                    self.click_timer = None
                self.click_timer = self.w1.spectrum.after(
                    300, lambda: self.show_zoom_plot(event)
                )  # Handle the single click after 300 milliseconds

    def spectrum_normalization(self, event):
        if event.dblclick and event.inaxes is not None:  # Require a double click inside a plot
            if self.click_timer:  # Cancel the timer to suppress the single-click action
                self.w1.spectrum.after_cancel(self.click_timer)
                self.click_timer = None

            self.nor_xdata = event.xdata
            self.nor_point_index = ((self.wavelength - event.xdata) ** 2).argmin()
            self.update_plot()
            if self.zoom_ax:
                self.plot_zoom_spectrum(self.zoom_ax)

    def reset_plot(self, event, zoom_ax=None):
        self.nor_point_index = None
        if zoom_ax:  # Handle a click inside the zoomed plot
            self.update_zoom_spectrum(event, zoom_ax)
        else:
            self.update_plot()
            if self.zoom_ax:
                self.plot_zoom_spectrum(self.zoom_ax)

    def show_zoom_plot(self, event):
        # Choose the plot from the clicked axes
        if event.inaxes == self.spectrum_ax:
            ax = self.spectrum_ax
            title = "Spectrum Plot"
        elif event.inaxes == self.time_ax:
            ax = self.time_ax
            title = "Time Series Plot"
        else:
            return

        # Create the zoom window
        zoom_dialog = tk.Toplevel()  # Create a separate top-level window
        zoom_dialog.title(title)

        # Create a new figure and canvas
        zoom_figure = Figure(figsize=(12, 8))
        zoom_canvas = FigureCanvasTkAgg(zoom_figure, master=zoom_dialog)

        # Copy the original traces to the new axes
        self.zoom_ax = zoom_figure.add_subplot(111)

        for line in ax.lines:
            marker = line.get_marker()
            if isinstance(marker, str):  # Check that the marker is a string
                markeredgecolor = line.get_markeredgecolor()
                self.zoom_ax.plot(
                    line.get_xdata(),
                    line.get_ydata(),
                    color=line.get_color(),
                    alpha=line.get_alpha(),
                    label=line.get_label(),
                    marker=marker,
                    markeredgecolor=markeredgecolor,
                    markersize=14,
                )
            else:
                self.zoom_ax.plot(
                    line.get_xdata(),
                    line.get_ydata(),
                    color=line.get_color(),
                    alpha=line.get_alpha(),
                    label=line.get_label(),
                    marker="",
                )  # Use an empty marker when its value is not a string.

        self.zoom_ax.set_title(ax.get_title(), fontsize=16)
        self.zoom_ax.set_xlabel(ax.get_xlabel(), fontsize=16)
        self.zoom_ax.set_ylabel(ax.get_ylabel(), fontsize=16)
        self.zoom_ax.tick_params(axis="both", labelsize=14)
        # self.zoom_ax.legend(loc="upper right", title='Spectra Index', fontsize=12, title_fontsize=12)

        zoom_toolbar = NavigationToolbar(zoom_canvas, zoom_dialog)
        zoom_toolbar.update()
        zoom_toolbar.pack(side=tk.TOP, fill=tk.X, anchor=tk.N)

        zoom_canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)

        zoom_canvas.draw()

        zoom_canvas.mpl_connect(
            "button_press_event", lambda event: self.update_zoom_spectrum(event, self.zoom_ax)
        )

    def update_zoom_spectrum(self, event, zoom_ax):
        if event.dblclick and event.inaxes is not None:  # Require a double click inside a plot
            self.nor_xdata = event.xdata
            self.nor_point_index = ((self.wavelength - event.xdata) ** 2).argmin()
            self.update_plot()
            self.plot_zoom_spectrum(zoom_ax)
        elif event.button == 2:
            self.nor_point_index = None
            self.update_plot()
            self.plot_zoom_spectrum(zoom_ax)

    def plot_zoom_spectrum(self, zoom_ax):
        zoom_ax.clear()
        result = data_reader(self.latest_file_path[self.selected_condition])
        conditions, data, grouped_conditions = result.Data_transfer()

        avg_spectrum = np.zeros_like(self.wavelength, dtype=float)

        cmap = plt.cm.RdPu
        colors = [
            cmap(0.2 + 0.6 * (i / (len(data) - 1))) for i in range(len(data))
        ]  # Avoid colors that are too light
        colors = [to_hex(c) for c in colors]

        for i in range(len(data)):
            y_data = data.iloc[i].values
            if self.nor_point_index:
                normalization_value = data.iloc[i].values[self.nor_point_index]
                y_data = y_data / normalization_value

            avg_spectrum += y_data
            if self.w1.average_var.get() == 0:
                zoom_ax.plot(self.wavelength, y_data, color=colors[i], label=i + 1)
        if self.w1.average_var.get() == 1:
            zoom_ax.plot(self.wavelength, avg_spectrum / len(data), color="#42A5F5")

        if self.nor_point_index:
            mark_intensity = y_data
            zoom_ax.plot(
                self.wavelength[self.nor_point_index],
                mark_intensity[self.nor_point_index],
                marker="*",
                color="yellow",
                markeredgecolor="black",
                markersize=12,
            )

        title = self.selected_condition
        zoom_ax.set_title(title)
        zoom_ax.set_xlabel("Wavelength (nm)")
        zoom_ax.set_ylabel("Intensity (a.u.)")
        (
            zoom_ax.yaxis.set_major_formatter(
                ticker.FuncFormatter(lambda x, pos: f"{int(x / 1000)}k")
            )
            if not self.nor_point_index
            else None
        )
        # zoom_ax.legend(loc="upper right", title='Spectra Index', fontsize=12, title_fontsize=12)

        zoom_canvas = zoom_ax.figure.canvas
        zoom_canvas.draw()

    # =============================================================================
    #         # Keep the window above other windows
    #         zoom_dialog = zoom_canvas.get_tk_widget().master
    #         zoom_dialog.attributes('-topmost', True)
    # =============================================================================

    def time_series_wavelength_change(self, event):
        if self.latest_file_path[self.selected_condition] and self.w1.time_series_list.get():
            self.plot_time_series()

    def normalize_wavelength_change(self, event):
        if self.w1.normalize_list.get() == "<Normalize>":
            self.nor_point_index = None
            self.update_plot()
        else:
            try:
                self.nor_point_index = (
                    (self.wavelength - float(self.w1.normalize_list.get())) ** 2
                ).argmin()
                self.update_plot()
            except:
                pass

    def update_plot(self, event=None):
        self.selected_condition = self.w1.spectrum_combobox.get()
        if self.selected_condition in self.latest_file_path:
            self.plot_spectrum()
            if self.w1.time_series_list.get():
                self.plot_time_series()
        else:
            print("Wrong in selecting condition")
            sys.stdout.flush()

    def load_latest_file_path(self):
        try:
            with open("log.json", "r") as f:
                data = json.load(f)
                return data.get("latest_file_path", {}), data.get("parameter_dict", {})
        except FileNotFoundError:
            return {}, {}  # Return two empty dictionaries when no history exists

    def save_latest_file_path(self):
        data = {"latest_file_path": self.latest_file_path, "parameter_dict": self.parameter_dict}
        with open("log.json", "w") as f:
            json.dump(data, f)


class StdoutRedirector:
    def __init__(self, text_widget, queue):
        self.text_widget = text_widget
        self.queue = queue

    def write(self, string):
        self.queue.put(string)

    def flush(self):
        pass

    def process_queue(self):
        try:
            while True:
                string = self.queue.get_nowait()
                self.text_widget.configure(state=tk.NORMAL)
                self.text_widget.insert(tk.END, string)
                self.text_widget.see(tk.END)
                self.text_widget.configure(state=tk.DISABLED)
                self.text_widget.update_idletasks()
        except queue.Empty:
            pass
        self.text_widget.after(100, self.process_queue)  # Poll the queue every 100 milliseconds


class data_reader:
    def __init__(self, txt_files):
        self.txt_files = txt_files
        self.column_index = [
            "Time",
            "Voltage",
            "Ontime",
            "Offtime",
            "Cycle",
            "Conductivity",
            "Metal1",
            "Metal2",
            "Metal3",
            "Metal4",
            "Metal5",
            "Run",
        ]
        self.wavelength = []

    def Wavelength_extraction(self):
        with open(self.txt_files[0], "r") as f:
            content = f.readlines()
            self.pixel_number = len(content)
            for i in range(self.pixel_number):
                self.wavelength.append(str(content[i].split("\t")[0]))
        return self.wavelength

    def Data_transfer(self):
        data_condition = []
        data_origin = []
        run = 1
        time = 0
        wavelength = self.Wavelength_extraction()
        is_background = False

        for file_path in self.txt_files:
            file_name = os.path.basename(file_path)
            parts = os.path.splitext(file_name)[0].rsplit("_", 11)
            if len(parts) == 12 and parts[-11] == "0":
                is_background = True
                break

        if not is_background:
            background = [0] * self.pixel_number

        for i, file_path in enumerate(self.txt_files):
            file_name = os.path.basename(file_path)
            parts = os.path.splitext(file_name)[0].rsplit("_", 11)

            if len(parts) != 12:
                # print(f"[WARNING] Filename format incorrect: {file_name}")
                continue

            try:
                float_parts = [
                    float(x) for x in parts[-11:]
                ]  # Convert the final 11 fields to floats, excluding the timestamp
            except ValueError:
                # print(f"[WARNING] Skipping non-numeric file: {file_name}")
                continue

            # Handle background files with zero on-time
            if parts[-11] == "0":
                with open(file_path, "r") as f:
                    content = f.readlines()
                    background = [
                        float(content[j].split("\t")[1]) for j in range(self.pixel_number)
                    ]

                # Infer the run index after the background file
                if data_condition and i + 1 < len(self.txt_files):
                    next_parts = os.path.splitext(os.path.basename(self.txt_files[i + 1]))[
                        0
                    ].rsplit("_", 11)[-11:]
                    try:
                        target_list = [float(x) for x in next_parts]
                        matching_rows = [
                            row[-1] for row in data_condition if row[1:-1] == target_list
                        ]
                        run = max(matching_rows) + 1 if matching_rows else 1
                    except ValueError:
                        run = 1
                time += 1

            else:
                data_condition.append([time] + float_parts + [run])

                with open(file_path, "r") as f:
                    content = f.readlines()
                    intensity = [
                        float(content[j].split("\t")[1]) - background[j]
                        for j in range(self.pixel_number)
                    ]
                    data_origin.append(intensity)

        condition = pd.DataFrame(data_condition, columns=self.column_index)
        data = pd.DataFrame(data_origin, columns=wavelength)

        grouped_conditions = condition.groupby(list(condition.columns)).apply(
            lambda x: x.index.tolist()
        )
        drop_indices = [indices[0] for indices in grouped_conditions if len(indices) > 1]

        condition = condition.drop(index=drop_indices).reset_index(drop=True)
        data = data.drop(index=drop_indices).reset_index(drop=True)
        grouped_conditions = condition.groupby(list(condition.columns)).apply(
            lambda x: x.index.tolist()
        )

        return condition, data, grouped_conditions


def on_closing(root):
    """Close the local GUI while retaining its acquisition history."""
    root.destroy()
    sys.exit(0)


def format_title(conditions):
    count = conditions.split(" ")[0]
    parameter = conditions.split(" ")[1]
    values = parameter.split("_")
    processed_values = []
    for value in values:
        try:
            float_value = float(value)
            if float_value.is_integer():  # Check whether the numeric value is integral
                processed_values.append(str(int(float_value)))
            else:
                processed_values.append(value)
        except ValueError:
            # Preserve values that cannot be converted to a float
            processed_values.append(value)

    # Reassemble the formatted values
    processed_param_str = f"{count} " + "_".join(processed_values)
    return processed_param_str


def load_time_series_config():
    return load_settings()["time_series_wavelength"]


def load_normalize_config():
    return ["<Normalize>"] + load_settings()["normalized_wavelength"]


if __name__ == "__main__":
    main()
